### ISSUE TITLE
Max interpolation error

### ISSUE THREAD

**Issue by ChenZhongPu** [learnedsystems/RadixSpline#1]
I am reading your `RadisSpline` paper, and I have doubt about the definition of `max interpolation error` as shown in Figure 2.

In my view, the error is defined as the deviation of position (`y` axis) given a key (`x` axis). Therefore, it should be depicted as a *vertical* line in the figure. Do I have some misunderstandings?

**Comment by andreaskipf** [comment]
You are correct. Thanks for pointing this out!
